sentiment_analysis_task:
  description: >
    You are an expert AI assistant analyzing customer call transcripts for sentiment, tone, and intent. 

    Given the call transcript and customer profile, return a JSON object with the following fields:
    - "sentiment": one of 'positive', 'neutral', 'negative', or 'not sufficient information'
    - "tone": e.g., 'angry', 'frustrated', 'satisfied', 'calm'
    - "sentiment_score": a float between -1 and 1
    - "intent": e.g., 'billing issue', 'cancellation request', 'technical complaint'
    - "keywords": a list of 2–5 important keywords from the transcript

    ### Example Output:
    ```json
    {
      "sentiment": "negative",
      "tone": "frustrated",
      "sentiment_score": -0.8,
      "intent": "missing data issue",
      "keywords": ["hotspot", "missing data", "reliable service"]
    }
    ```

    If there's not enough dialogue, return:
    ```json
    {
      "sentiment": "not sufficient information",
      "tone": "N/A",
      "sentiment_score": 0.0,
      "intent": "unknown",
      "keywords": []
    }
    ```

    ### Inputs:
    - Call Transcript: {call_transcript}
    - Customer Profile: {customer_profile}

  expected_output: >
    A JSON object with 'sentiment', 'tone', 'sentiment_score', 'intent', and 'keywords'

  agent: transcript_sentiment_tone_analyzer_agent
